## I: Abstract
As we enter the 3rd decade of the 21st century, the disastrous effects of climate change are becoming more and more clear and at some point, will become irreversible.  According to NASA, carbon dioxide levels are the highest they have been in 650,000 years and the global temperature has risen 2 degrees Fahrenheit since 1880.  In addition, the polar ice sheets are losing 427 billion metric tons per year and sea level rises 3.3 millimeters per year.  Scientists have reported that global temperatures could reach an irreversible tipping point by 2030 if drastic measures are not taken to slow down the rapidly occurring climate change.  In addition to environmental impact assessment, mitigation strategies must be set into place in order to insure that future generations will continue to be able to live on a habitable planet.

## II: Introduction
One way to minimize the amount of carbon released into the atmosphere is through the use of solar panels as a source of renewable energy.  In this project, using a combination of data science methods and thorough research, I will propose a mitigation strategy that requires certain homeowners, based on the purchase price of their house, to install solar panels as a way of reducing carbon emissions.  I will first use a dataset containing the annual number of metric tons of carbon emissions for certain cities in the United States.  While it would be interesting to see the carbon emissions from every city in the U.S. this project will be on a smaller scale, only looking at prominent cities across the country.  I will then look at more data containing median housing prices for these same specific cities.  Exploring the data and using basic math will allow me to find the percentage change in carbon emissions per city as an indicator of how well my proposal will work.  In the end, I would like to see the percentage change in carbon emissions per city if certain housing owners are required to install solar panels.

## III: Data

## IV: Exploratory Data Analysis

## V: Analysis and Discussion

## VI: Conclusion

$$ Conversion Rate \cdot 6351kWh \cdot Number of Houses = CO2 Saved $$

## VII: References
1. https://data.cdp.net/Emissions/2016-Citywide-Emissions-Map/iqbu-zjaj
2. https://climate.nasa.gov/
3. https://abcnews.go.com/International/united-nations-report-details-looming-climate-crisis/story?id=58354235
4. Zillow.com
5. https://www.point2homes.com/US/Neighborhood/IL/Lake-Forest-Demographics.html
6. https://www.neighborhoodscout.com/il/alton/real-estate
7. https://www.census.gov/quickfacts/
8. https://en.wikipedia.org/wiki/Brisbane,_California
10. 

## VIII: Appendix
